import { PaintType } from "../../shared/recipaint/paints";
import catalogueJson from "../data/paintCatalogue.json";

// The shared paint catalogue: 2,164 real paints across Citadel Colour, Vallejo, Army Painter
// and Scale75, generated by scripts/build-paint-catalogue.ts from the MIT-licensed
// `miniature-paints` dataset.
//
// Static reference data, so it is a committed JSON rather than a Mongo collection - nothing
// to seed, nothing to keep in sync, and no drift between the database and the source. At this
// size an in-memory scan is sub-millisecond, which is the whole reason a collection would buy
// nothing.
//
// It lives under src/server/ on purpose: nothing in src/client/ can import it, so half a
// megabyte of reference data can never be pulled into the browser bundle by accident.

export interface CataloguePaint {
  key: string;
  brand: string;
  name: string;
  range: string;
  hex: string;
  type: PaintType | "";
  /** Lowercased "brand range name". Precomputed so a query is one includes() per row. */
  search: string;
}

const CATALOGUE = catalogueJson as CataloguePaint[];

const BY_KEY = new Map(CATALOGUE.map((paint) => [paint.key, paint]));

const BRANDS = [...new Set(CATALOGUE.map((paint) => paint.brand))].sort((a, b) => a.localeCompare(b));

export const DEFAULT_SEARCH_LIMIT = 25;
export const MAX_SEARCH_LIMIT = 100;

export interface SearchOptions {
  q?: string;
  brand?: string;
  limit?: number;
}

/**
 * Substring search over brand, range and name.
 *
 * An empty query returns the first page rather than everything, so the endpoint can never be
 * used to pull the whole catalogue in one request.
 */
export function searchCatalogue({ q, brand, limit }: SearchOptions = {}): CataloguePaint[] {
  const needle = (q || "").trim().toLowerCase();
  const wantedBrand = (brand || "").trim().toLowerCase();
  // Same shape as parsePaging() in routes/recipaint.ts: a junk, zero or negative limit falls
  // back to the default rather than being clamped to some arbitrary edge value.
  const cap =
    Number.isFinite(limit) && (limit as number) > 0
      ? Math.min(Math.floor(limit as number), MAX_SEARCH_LIMIT)
      : DEFAULT_SEARCH_LIMIT;

  const results: CataloguePaint[] = [];
  for (const paint of CATALOGUE) {
    if (wantedBrand && paint.brand.toLowerCase() !== wantedBrand) continue;
    if (needle && !paint.search.includes(needle)) continue;
    results.push(paint);
    if (results.length >= cap) break;
  }
  return results;
}

export function getCataloguePaint(key: string): CataloguePaint | null {
  return BY_KEY.get(key) || null;
}

export function listCatalogueBrands(): string[] {
  return BRANDS;
}

export function catalogueSize(): number {
  return CATALOGUE.length;
}
